# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Nimbus API
tagline:          'A Messaging API for Cloud Applications'
description:      'Nimbus API is a .NET API for building messaging applications with Azure Service Bus, Windows Service Bus, and Redis'
url:              http:/nimbusapi.com
baseurl:          /

author:
  name:           'NimbusAPI'
  url:            https://twitter.com/nimbusapi

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/nimbusapi/nimbus

gems:             [jekyll-paginate]