# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nimbus API
tagline:          'A Messaging API for Cloud Applications'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http:/nimbusapi.com
baseurl:          /

author:
  name:           'NimbusAPI'
  url:            https://twitter.com/nimbusapi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nimbusapi/nimbus
